sudo: required
services:
  - docker

before_install:
  - docker build -t rabbani8/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run rabbani8/react-test npm test -- --coverage

after_success:
  - docker build -t rabbani8/docker-multi-client ./client/
  - docker build -t rabbani8/docker-multi-server ./server/
  - docker build -t rabbani8/docker-multi-nginx  ./nginx/
  - docker build -t rabbani8/docker-multi-worker ./worker/
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rabbani8/docker-multi-client
  - docker push rabbani8/docker-multi-server
  - docker push rabbani8/docker-multi-nginx
  - docker push rabbani8/docker-multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker-multi-container
  env: DockerMultiContainer-env
  bucket_name: elasticbeanstalk-ap-south-1-635584874543
  bucket_path: docker-multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
